ci: coverage test 시 postgre docker 설정
  Test에 필요한 postgrer가 github action에서 작동 될 수 있도록 설정.

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -1,12 +1,12 @@
-name: "Jest"
+name: 'Jest'
 on:
   push:
     branches:
-      - "develop"
+      - 'develop'
   pull_request:
     branches:
-      - "develop"
-      - "migration"
+      - 'develop'
+      - 'migration'
       # - '*'         # matches every branch that doesn't contain a '/'
       # - '*/*'       # matches every branch containing a single '/'
       # - '**'        # matches every branch
@@ -29,7 +29,13 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: '18' # ${{ matrix.node }}
-      
+
+      - name: Set up postgre docker
+        run: yarn docker:local local-db
+
+      - name: Check docker
+        run: docker ps
+
       - name: Cache dependencies
         id: cache
         uses: actions/cache@v3
@@ -49,33 +55,36 @@ jobs:
         if: steps.cache.outputs.cache-hit != 'true'
         run: yarn install
 
+      - name: wait for db
+        run: export NODE_ENV=local && yarn wait-db
+
       - name: Run e2e test ✅
         uses: ArtiomTr/jest-coverage-report-action@v2
         id: coverage
         with:
-            package-manager: yarn
-            test-script: yarn test:api:e2e:cov
-            skip-step: install
-            output: comment, report-markdown
-            custom-title: e2e-test > local
-      
+          package-manager: yarn
+          test-script: yarn test:api:e2e:cov
+          skip-step: install
+          output: comment, report-markdown
+          custom-title: e2e-test > local
+
       - name: Detailed report with junit
         uses: dorny/test-reporter@v1
-        if: success() || failure()    # run this step even if previous step failed
+        if: success() || failure() # run this step even if previous step failed
         with:
           name: test-results
           path: jest-junit.xml
           fail-on-error: 'false'
-          reporter: jest-junit        # Format of test results
+          reporter: jest-junit # Format of test results
           token: ${{ secrets.GITHUB_TOKEN }}
 
     # Push Slack
-      # - name: Push to slack
-      #   uses: 8398a7/action-slack@v3
-      #   with:
-      #     status: ${{ job.status }}
-      #     author_name: Github Action Test # default: 8398a7@action-slack
-      #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
-      #   env:
-      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URI }} # required
-      #   if: always() # Pick up events even if the job fails or is canceled.
+    # - name: Push to slack
+    #   uses: 8398a7/action-slack@v3
+    #   with:
+    #     status: ${{ job.status }}
+    #     author_name: Github Action Test # default: 8398a7@action-slack
+    #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
+    #   env:
+    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URI }} # required
+    #   if: always() # Pick up events even if the job fails or is canceled.
